"""changed htmlcontent to content

Revision ID: 304404fc9685
Revises: 
Create Date: 2024-08-28 23:51:52.187125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '304404fc9685'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_column('htmlcontent')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('htmlcontent', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('content')
